// Delivery Window Scheduler
// Schedule and manage delivery windows with conflict detection, priority routing, and SLA compliance tracking for last-mile logistics.
// Auto-generated by @ph-itdev/logistics-pipeline


class DeliveryWindowScheduler {
  constructor({ businessHours = { start: 8, end: 18 } } = {}) {
    this.windows = new Map();
    this.bookings = [];
    this.businessHours = businessHours;
  }
  createWindow(id, { date, startHour, endHour, maxDeliveries = 5, zone = 'default' }) {
    if (startHour < this.businessHours.start || endHour > this.businessHours.end)
      throw new Error(`Window must be within business hours (${this.businessHours.start}-${this.businessHours.end})`);
    this.windows.set(id, { id, date, startHour, endHour, maxDeliveries, zone, bookings: [] });
  }
  bookDelivery(windowId, { orderId, address, priority = 'normal', etaMinutes = 30 }) {
    const w = this.windows.get(windowId);
    if (!w) throw new Error('Window not found');
    if (w.bookings.length >= w.maxDeliveries) throw new Error('Window is full');
    const conflict = w.bookings.find(b => b.orderId === orderId);
    if (conflict) throw new Error('Order already booked in this window');
    const sla = { promisedBy: w.endHour, estimatedDelivery: w.startHour + (etaMinutes / 60), priority };
    sla.compliant = sla.estimatedDelivery <= sla.promisedBy || priority === 'urgent';
    const booking = { orderId, address, priority, etaMinutes, windowId, ts: Date.now(), sla };
    w.bookings.push(booking);
    this.bookings.push(booking);
    return booking;
  }
  cancelBooking(windowId, orderId) {
    const w = this.windows.get(windowId);
    if (!w) throw new Error('Window not found');
    const idx = w.bookings.findIndex(b => b.orderId === orderId);
    if (idx === -1) throw new Error('Booking not found');
    w.bookings.splice(idx, 1);
    this.bookings = this.bookings.filter(b => !(b.windowId === windowId && b.orderId === orderId));
  }
  getWindowStatus(windowId) {
    const w = this.windows.get(windowId);
    if (!w) throw new Error('Window not found');
    return { id: w.id, date: w.date, hours: `${w.startHour}:00-${w.endHour}:00`, zone: w.zone, filled: w.bookings.length, capacity: w.maxDeliveries, available: w.maxDeliveries - w.bookings.length };
  }
  getSLAReport() {
    const total = this.bookings.length;
    const compliant = this.bookings.filter(b => b.sla.compliant).length;
    return { total, compliant, violations: total - compliant, complianceRate: total ? +((compliant / total) * 100).toFixed(1) : 100 };
  }
  getOverbookedWindows() {
    return [...this.windows.values()].filter(w => w.bookings.length >= w.maxDeliveries).map(w => ({ id: w.id, date: w.date, zone: w.zone }));
  }
}


module.exports = { DeliveryWindowScheduler };
